// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;
import edu.wpi.first.math.util.Units;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */ 

      public static final double MAX_SPEED  = Units.feetToMeters(14.5);

    public static class CanIds {
    // Can id 1-8 are for the drive train
    // public static final int TOWER_MOTOR_RIGHT1 = 11;
    // public static final int TOWER_MOTOR_LEFT1 = 12;
    // public static final int TOWER_MOTOR_RIGHT2 = 13;
    // public static final int TOWER_MOTOR_LEFT2 = 14;
    // public static final int FEEDER_MOTOR = 15;
    // public static final int INTAKE_MOTOR = 16;
    // public static final int CLIMBER_MOTOR = 17;
    // public static final int FUNNEL_MOTOR = 18;
    // public static final int EXTEND_MOTOR = 19;
    // public static final int RCLIMB_MOTOR = 20;
    // public static final int LCLIMB_MOTOR = 21;
    // public static final int TURN_MOTOR = 22;

    // create enum to store motor name, subsystem, can id, and SparkMaxConfig object data for easy reference.
    public enum MOTORS {
        TOWER1_MOTOR_RIGHT("Tower 1 Motor Right", "Flywheels", 9),
        TOWER1_MOTOR_LEFT("Tower 1 Motor Left", "Flywheels", 10),
        TOWER2_MOTOR_RIGHT("Tower 2 Motor Right", "Flywheels", 11),
        TOWER2_MOTOR_LEFT("Tower 2 Motor Left", "Flywheels", 12),
        FEEDER_MOTOR("Feeder Motor", "Hopper", 13),
        INTAKE_MOTOR("Intake Motor", "Intake", 14),
        CLIMBER_MOTOR("Climber Motor", "Climb", 15),
        FUNNEL_MOTOR("Funnel Motor", "Hopper", 16),
        EXTEND_MOTOR("Extend Motor", "Intake", 17),
        RCLIMB_MOTOR("Right Climb Motor", "Climb", 18),
        LCLIMB_MOTOR("Left Climb Motor", "Climb", 19),
        TURN_MOTOR("Turret Turn Motor", "LTurret", 20);

        public final String motorName;
        public final String subSystem;
        public final int canId;

        MOTORS(String motorName, String subSystem, int canId) {
            this.motorName = motorName;
            this.subSystem = subSystem;
            this.canId = canId;
        }
    }
    
  }
}

