// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */ 

    public static class CanIds {
    // Can id 1-8 are for the drive train
    public static final int TOWER_MOTOR_RIGHT1 = 11;
    public static final int TOWER_MOTOR_LEFT1 = 12;
    public static final int TOWER_MOTOR_RIGHT2 = 13;
    public static final int TOWER_MOTOR_LEFT2 = 14;
    public static final int FEEDER_MOTOR = 15;
    public static final int INTAKE_MOTOR = 16;
    public static final int CLIMBER_MOTOR = 17;
    public static final int FUNNEL_MOTOR = 18;
    public static final int EXTEND_MOTOR = 19;
    public static final int RCLIMB_MOTOR = 20;
    public static final int LCLIMB_MOTOR = 21;
    public static final int TURN_MOTOR = 22;
  }
}

