// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.Constants.CanIds;
import frc.robot.commands.*;

import com.revrobotics.spark.SparkMax;
import com.revrobotics.spark.config.SparkBaseConfig.IdleMode;
import com.revrobotics.spark.config.SparkMaxConfig;
import javax.lang.model.util.ElementScanner14;
import com.revrobotics.spark.ClosedLoopSlot;
import com.revrobotics.spark.FeedbackSensor;
import com.revrobotics.spark.SparkBase.ControlType;
import com.revrobotics.spark.SparkBase.PersistMode;
import com.revrobotics.spark.SparkLowLevel.MotorType;
import com.revrobotics.spark.SparkBase.ResetMode;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Climb extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final double MaxRpm = 0;

    private SparkMax rClimbMotor = new SparkMax(CanIds.RCLIMB_MOTOR, MotorType.kBrushless);
    private SparkMax lClimbMotor = new SparkMax(CanIds.LCLIMB_MOTOR, MotorType.kBrushless);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final double Start = 1.0;
    private final double Stop = 0.0;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private SparkMaxConfig rClimbConfig = new SparkMaxConfig();
    private SparkMaxConfig lClimbConfig = new SparkMaxConfig();
    /**
    *
    */
    public Climb() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    private void configrClimbMotor() {


        // config.encoder.positionConversionFactor(Math.PI * elevator_gearDiameter /
        // elevator_gearRatio);
        rClimbConfig.encoder.positionConversionFactor(1);
        rClimbConfig.inverted(true);
        rClimbConfig.softLimit.forwardSoftLimitEnabled(false);
        rClimbConfig.softLimit.reverseSoftLimit(0);
        rClimbConfig.softLimit.reverseSoftLimitEnabled(false);
        rClimbConfig.idleMode(IdleMode.kCoast);
        rClimbConfig.openLoopRampRate(0.15);
        //rClimbConfig.limitSwitch.forwardLimitSwitchEnabled(false);
        //rClimbConfig.limitSwitch.reverseLimitSwitchEnabled(false);

        rClimbConfig.closedLoop.maxOutput(1.0);
        rClimbConfig.closedLoop.minOutput(-1.0);

        rClimbConfig.closedLoopRampRate(0.15);
        rClimbConfig.voltageCompensation(9.0);
        //// Down / outVelocity Values
        // rClimbConfig.closedLoop.maxMotion.maxAcceleration(5000, rClimb_CLOSED_LOOP_SLOT_DOWN);
        // rClimbConfig.closedLoop.maxMotion.maxVelocity(5000, rClimb_CLOSED_LOOP_SLOT_DOWN);
        // rClimbConfig.closedLoop.maxMotion.allowedClosedLoopError(rClimbPosTol, rClimb_CLOSED_LOOP_SLOT_DOWN);
        // rClimbConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rClimb_CLOSED_LOOP_SLOT_DOWN);

        // //// Up / in Velocity Values
        // rClimbConfig.closedLoop.maxMotion.maxAcceleration(5000, rClimb_CLOSED_LOOP_SLOT_UP);
        // rClimbConfig.closedLoop.maxMotion.maxVelocity(2000, rClimb_CLOSED_LOOP_SLOT_UP);
        // rClimbConfig.closedLoop.maxMotion.allowedClosedLoopError(rClimbPosTol, rClimb_CLOSED_LOOP_SLOT_UP);
        // rClimbConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rClimb_CLOSED_LOOP_SLOT_UP);

        rClimbConfig.closedLoop.feedbackSensor(FeedbackSensor.kPrimaryEncoder);

        // config.smartCurrentLimit(50);
        //Config.smartCurrentLimit(normalStallCurrentLimit, normalFreeCurrentLimit);

        //rClimbMotor.configure(rClimbConfig, ResetMode.kResetSafeParameters, PersistMode.kPersistParameters);

    }

    private void configlClimbMotor() {


        // config.encoder.positionConversionFactor(Math.PI * elevator_gearDiameter /
        // elevator_gearRatio);
        lClimbConfig.encoder.positionConversionFactor(1);
        lClimbConfig.inverted(true);
        lClimbConfig.softLimit.forwardSoftLimitEnabled(false);
        lClimbConfig.softLimit.reverseSoftLimit(0);
        lClimbConfig.softLimit.reverseSoftLimitEnabled(false);
        lClimbConfig.idleMode(IdleMode.kCoast);
        lClimbConfig.openLoopRampRate(0.15);
        //lClimbConfig.limitSwitch.forwardLimitSwitchEnabled(false);
        //lClimbConfig.limitSwitch.reverseLimitSwitchEnabled(false);

        lClimbConfig.closedLoop.maxOutput(1.0);
        lClimbConfig.closedLoop.minOutput(-1.0);
        lClimbConfig.closedLoopRampRate(0.15);
        lClimbConfig.voltageCompensation(9.0);
        //// Down / outVelocity Values
        // lClimbConfig.closedLoop.maxMotion.maxAcceleration(5000, lClimb_CLOSED_LOOP_SLOT_DOWN);
        // lClimbConfig.closedLoop.maxMotion.maxVelocity(5000, lClimb_CLOSED_LOOP_SLOT_DOWN);
        // lClimbConfig.closedLoop.maxMotion.allowedClosedLoopError(lClimbPosTol, lClimb_CLOSED_LOOP_SLOT_DOWN);
        // lClimbConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, lClimb_CLOSED_LOOP_SLOT_DOWN);

        // //// Up / in Velocity Values
        // lClimbConfig.closedLoop.maxMotion.maxAcceleration(5000, lClimb_CLOSED_LOOP_SLOT_UP);
        // lClimbConfig.closedLoop.maxMotion.maxVelocity(2000, lClimb_CLOSED_LOOP_SLOT_UP);
        // lClimbConfig.closedLoop.maxMotion.allowedClosedLoopError(lClimbPosTol, lClimb_CLOSED_LOOP_SLOT_UP);
        // lClimbConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, lClimb_CLOSED_LOOP_SLOT_UP);

        lClimbConfig.closedLoop.feedbackSensor(FeedbackSensor.kPrimaryEncoder);

        // config.smartCurrentLimit(50);
        //lClimbConfig.smartCurrentLimit(normalStallCurrentLimit, normalFreeCurrentLimit);

        //lClimbMotor.configure(lClimbConfig, ResetMode.kResetSafeParameters, PersistMode.kPersistParameters);

    }

    public enum ClimbPos {
        START (0.0, 0.0),
        EXTENDED (0.0, 0.0),
        HOLDING (0.0, 0.0);

        private final double rightPos;
        private final double leftPos;
        
        ClimbPos(double rightPos, double leftPos) {
            this.rightPos = rightPos;
            this.leftPos = leftPos;
        }

        public double getRightPos() {
            return rightPos;
        }

        public double getLeftPos() {
            return leftPos;
        }
    }

}

