// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import frc.robot.Constants.CanIds;
import frc.robot.commands.*;

import com.revrobotics.spark.SparkMax;
import com.revrobotics.spark.config.SparkBaseConfig.IdleMode;
import com.thethriftybot.interfaces.DriverStationInterface;
import com.revrobotics.spark.config.SparkMaxConfig;

import java.io.ObjectInputFilter.Status;

import javax.lang.model.util.ElementScanner14;
import com.revrobotics.spark.ClosedLoopSlot;
import com.revrobotics.spark.FeedbackSensor;
import com.revrobotics.spark.SparkBase.ControlType;
import com.revrobotics.spark.SparkBase.PersistMode;
import com.revrobotics.spark.SparkLowLevel.MotorType;
import com.revrobotics.spark.SparkBase.ResetMode;

import edu.wpi.first.units.measure.Time;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import edu.wpi.first.wpilibj.DriverStation;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class FMSSystem extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final double MaxRpm = 0;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final double Start = 1.0;
    private final double Stop = 0.0;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private Timer time = new Timer();
    private FMSStatus status = FMSStatus.PREMATCH;
    private double remainingTime = 0.0;

    private String gameData = DriverStation.getGameSpecificMessage();
       //need way to access the Field management system and read the alliance shift data

    /**
    *
    */
    public FMSSystem() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        // switch statement that changes the status based on the runtime match time
        double elapsed = time.get();
        switch (status) {
            case PREMATCH:
                // do nothing
                break;
            case AUTONOMOUS:
<<<<<<< Updated upstream
                // do nothing
                remainingTime = 15 - elapsed;
                if (elapsed >= 25) {
                    setStatus(FMSStatus.PRETELEOP);
                }
                // do nothing
                break;
            case PRETELEOP:
                // do nothing
                remainingTime = 5 - elapsed;
=======
                resetAuton();
                remainingTime = 25 - elapsed;
            if (elapsed >= 25) {
             setStatus(FMSStatus.PRETELEOP);
            }
                break;
            case PRETELEOP:
                remainingTime = 28 - elapsed;
>>>>>>> Stashed changes
                if (elapsed >= 28) {
                    resetTeleop();
                }
                break;
            case TRANSITION:
<<<<<<< Updated upstream
                // do nothing
=======
>>>>>>> Stashed changes
                remainingTime = 10 - elapsed;
                if (elapsed >= 10) {
                    setStatus(FMSStatus.ALLIANCE_SHIFT_1);
                }
                break;
            case ALLIANCE_SHIFT_1:
<<<<<<< Updated upstream
                // do nothing
                // timeremaining = 35 - time
=======
>>>>>>> Stashed changes
                remainingTime = 35 - elapsed;
                if (elapsed >= 35) {
                    setStatus(FMSStatus.ALLIANCE_SHIFT_2);
                }
                break;
            case ALLIANCE_SHIFT_2:
                // do nothing
                remainingTime = 60 - elapsed;
<<<<<<< Updated upstream
                if (elapsed >= 60) {
                    setStatus(FMSStatus.ALLIANCE_SHIFT_3);
=======
                 if (elapsed >= 60) {
            setStatus(FMSStatus.ALLIANCE_SHIFT_3);
>>>>>>> Stashed changes
                }
                break;
            case ALLIANCE_SHIFT_3:
                // do nothing
                remainingTime = 85 - elapsed;
                if (elapsed >= 85) {
                    setStatus(FMSStatus.ALLIANCE_SHIFT_4);
                }
                break;
            case ALLIANCE_SHIFT_4:
                // do nothing
                remainingTime = 110 - elapsed;
                if (elapsed >= 110) {
                    setStatus(FMSStatus.ENDGAME);
                }
                break;
            case ENDGAME:
                // do nothing
                remainingTime = 140 - elapsed;
<<<<<<< Updated upstream
                if (elapsed >= 140) {
                    setStatus(FMSStatus.POSTMATCH);
=======
                    if (elapsed >= 140) {
                setStatus(FMSStatus.POSTMATCH);
>>>>>>> Stashed changes
                }
                break;
            case POSTMATCH:
                // do nothing
                break;
            default:
                // do nothing
                break;
        }
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public FMSStatus getStatus() {
        return status;
    }

    private void setStatus(FMSStatus status) {
        // do nothing for now
        this.status = status;
    }

    public void startTeleop() {
        time.start();
    }

    public void pause() {
        time.stop();
    }

    public void resetTeleop() {
        time.start();
        time.reset();
        setStatus(FMSStatus.TRANSITION);
    }

    public void resetAuton() {
        time.start();
        time.reset();
        setStatus(FMSStatus.AUTONOMOUS);
    }

    public double getRemainingTime() {
        return remainingTime;
    }

    public String getPrivateData() {
        return gameData;
    }

   



    // enum that has status of prematch, Auton, transition, alliance shift 1,
    // alliance shift 2, alliance shift 3, alliance shift 4, endgame
    public enum FMSStatus {
        PREMATCH,
        AUTONOMOUS,
        PRETELEOP,
        TRANSITION,
        ALLIANCE_SHIFT_1,
        ALLIANCE_SHIFT_2,
        ALLIANCE_SHIFT_3,
        ALLIANCE_SHIFT_4,
        ENDGAME,
        POSTMATCH;

    }
}
