// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.Constants.CanIds;
import frc.robot.commands.*;

import com.revrobotics.spark.SparkMax;
import com.revrobotics.spark.config.SparkBaseConfig.IdleMode;
import com.revrobotics.spark.config.SparkMaxConfig;
import javax.lang.model.util.ElementScanner14;
import com.revrobotics.spark.ClosedLoopSlot;
import com.revrobotics.spark.FeedbackSensor;
import com.revrobotics.spark.SparkBase.ControlType;
import com.revrobotics.PersistMode;
import com.revrobotics.spark.SparkLowLevel.MotorType;
import com.revrobotics.ResetMode;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Hopper extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final double MaxRpm = 0;

    private boolean bAuthToFireHum = false;

    private SparkMax beltMotor = new SparkMax(CanIds.MOTORS.FEEDER_MOTOR.canId, MotorType.kBrushless);
    private SparkMax funnelMotor = new SparkMax(CanIds.MOTORS.FUNNEL_MOTOR.canId, MotorType.kBrushless);
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private HopperStatus status = HopperStatus.STOP;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private SparkMaxConfig beltMotorConfig = new SparkMaxConfig();
    private SparkMaxConfig FunnelConfig = new SparkMaxConfig();

    /**
    *
    */
    public Hopper() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        configBeltMotor();
        configFunnelMotor();

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    public boolean getbAuthToFireHum (){
        return bAuthToFireHum;
    }

    public void setbAuthToFieHum (boolean bAuth) {
        this.bAuthToFireHum = bAuth;
        
    }


public HopperStatus getStatus() {
        return status;
    }

    public void setStatus(HopperStatus status) {
        this.status = status;
        beltMotor.setVoltage(status.getBeltMotorVoltage());
        funnelMotor.setVoltage(status.getFunnelMotorVoltage());
    }


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    private void configBeltMotor() {


        // config.encoder.positionConversionFactor(Math.PI * elevator_gearDiameter /
        // elevator_gearRatio);
        beltMotorConfig.encoder.positionConversionFactor(1);
        beltMotorConfig.inverted(true);
        beltMotorConfig.softLimit.forwardSoftLimitEnabled(false);
        beltMotorConfig.softLimit.reverseSoftLimit(0);
        beltMotorConfig.softLimit.reverseSoftLimitEnabled(false);
        beltMotorConfig.idleMode(IdleMode.kCoast);
        beltMotorConfig.openLoopRampRate(0.15);
        //beltMotorConfig.limitSwitch.forwardLimitSwitchEnabled(false);
        //beltMotorConfig.limitSwitch.reverseLimitSwitchEnabled(false);

        beltMotorConfig.closedLoop.maxOutput(1.0);
        beltMotorConfig.closedLoop.minOutput(-1.0);

        beltMotorConfig.closedLoopRampRate(0.15);
        beltMotorConfig.voltageCompensation(9.0);
        //// Down / outVelocity Values
        // beltMotorConfig.closedLoop.maxMotion.maxAcceleration(5000, beltMotor_CLOSED_LOOP_SLOT_DOWN);
        // beltMotorConfig.closedLoop.maxMotion.maxVelocity(5000, beltMotor_CLOSED_LOOP_SLOT_DOWN);
        // beltMotorConfig.closedLoop.maxMotion.allowedClosedLoopError(beltMotorPosTol, beltMotor_CLOSED_LOOP_SLOT_DOWN);
        // beltMotorConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, beltMotor_CLOSED_LOOP_SLOT_DOWN);

        // //// Up / in Velocity Values
        // beltMotorConfig.closedLoop.maxMotion.maxAcceleration(5000, beltMotor_CLOSED_LOOP_SLOT_UP);
        // beltMotorConfig.closedLoop.maxMotion.maxVelocity(2000, beltMotor_CLOSED_LOOP_SLOT_UP);
        // beltMotorConfig.closedLoop.maxMotion.allowedClosedLoopError(beltMotorPosTol, beltMotor_CLOSED_LOOP_SLOT_UP);
        // beltMotorConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, beltMotor_CLOSED_LOOP_SLOT_UP);

        beltMotorConfig.closedLoop.feedbackSensor(FeedbackSensor.kPrimaryEncoder);

        beltMotorConfig.smartCurrentLimit(30);
        //beltMotorConfig.smartCurrentLimit(normalStallCurrentLimit, normalFreeCurrentLimit);

        beltMotor.configure(beltMotorConfig, ResetMode.kResetSafeParameters, PersistMode.kPersistParameters);

    }

    private void configFunnelMotor() {


        // config.encoder.positionConversionFactor(Math.PI * elevator_gearDiameter /
        // elevator_gearRatio);
        FunnelConfig.encoder.positionConversionFactor(1);
        FunnelConfig.inverted(true);
        FunnelConfig.softLimit.forwardSoftLimitEnabled(false);
        FunnelConfig.softLimit.reverseSoftLimit(0);
        FunnelConfig.softLimit.reverseSoftLimitEnabled(false);
        FunnelConfig.idleMode(IdleMode.kCoast);
        FunnelConfig.openLoopRampRate(0.15);
        //FunnelConfig.limitSwitch.forwardLimitSwitchEnabled(false);
        //FunnelConfig.limitSwitch.reverseLimitSwitchEnabled(false);
        FunnelConfig.closedLoop.maxOutput(1.0);
        FunnelConfig.closedLoop.minOutput(-1.0);

        FunnelConfig.closedLoopRampRate(0.15);
        FunnelConfig.voltageCompensation(9.0);
        //// Down / outVelocity Values
        // FunnelConfig.closedLoop.maxMotion.maxAcceleration(5000, rFunnelMotor_CLOSED_LOOP_SLOT_DOWN);
        // FunnelConfig.closedLoop.maxMotion.maxVelocity(5000, rFunnelMotor_CLOSED_LOOP_SLOT_DOWN);
        // FunnelConfig.closedLoop.maxMotion.allowedClosedLoopError(rFunnelMotorPosTol, rFunnelMotor_CLOSED_LOOP_SLOT_DOWN);
        // FunnelConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rFunnelMotor_CLOSED_LOOP_SLOT_DOWN);

        // //// Up / in Velocity Values
        // FunnelConfig.closedLoop.maxMotion.maxAcceleration(5000, rFunnelMotor_CLOSED_LOOP_SLOT_UP);
        // FunnelConfig.closedLoop.maxMotion.maxVelocity(2000, rFunnelMotor_CLOSED_LOOP_SLOT_UP);
        // FunnelConfig.closedLoop.maxMotion.allowedClosedLoopError(rFunnelMotorPosTol, rFunnelMotor_CLOSED_LOOP_SLOT_UP);
        // FunnelConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rFunnelMotor_CLOSED_LOOP_SLOT_UP);

        FunnelConfig.closedLoop.feedbackSensor(FeedbackSensor.kPrimaryEncoder);

        FunnelConfig.smartCurrentLimit(30);
        //FunnelConfig.smartCurrentLimit(normalStallCurrentLimit, normalFreeCurrentLimit);

        funnelMotor.configure(FunnelConfig, ResetMode.kResetSafeParameters, PersistMode.kPersistParameters);
       
    }

    //create enumeration to track status of hopper
    //for each entry create belt motor voltage and funnel motor voltage
    public enum HopperStatus {
        STOP(0.0, 0.0),
        INDEXING(0.0,0.0),
        FUELING(10.0,6.0),
        REVERSAL(-5.0,-5.0);

        public final double beltMotorVoltage;
        public final double funnelMotorVoltage;
    
        HopperStatus(double beltMotorVoltage, double funnelMotorVoltage) {  
            this.beltMotorVoltage = beltMotorVoltage;
            this.funnelMotorVoltage = funnelMotorVoltage;
        }
        public double getBeltMotorVoltage() {
            return beltMotorVoltage;
        }
        public double getFunnelMotorVoltage() {
            return funnelMotorVoltage;
        }
    
    }

}

