// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.Constants.CanIds;
import frc.robot.commands.*;

import com.revrobotics.spark.SparkMax;
import com.revrobotics.spark.config.SparkBaseConfig.IdleMode;
import com.revrobotics.spark.config.SparkMaxConfig;
import javax.lang.model.util.ElementScanner14;
import com.revrobotics.spark.ClosedLoopSlot;
import com.revrobotics.spark.FeedbackSensor;
import com.revrobotics.spark.SparkBase.ControlType;
import com.revrobotics.spark.SparkBase.PersistMode;
import com.revrobotics.spark.SparkLowLevel.MotorType;
import com.revrobotics.spark.SparkBase.ResetMode;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Feeder extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final double MaxRpm = 0;

    private SparkMax beltMotor = new SparkMax(CanIds.FEEDER_MOTOR, MotorType.kBrushless);
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final double Start = 1.0;
    private final double Stop = 0.0;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private SparkMaxConfig beltMotorConfig = new SparkMaxConfig();

    /**
    *
    */
    public Feeder() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    private void configBeltMotor() {


        // config.encoder.positionConversionFactor(Math.PI * elevator_gearDiameter /
        // elevator_gearRatio);
        beltMotorConfig.encoder.positionConversionFactor(1);
        beltMotorConfig.inverted(true);
        beltMotorConfig.softLimit.forwardSoftLimitEnabled(false);
        beltMotorConfig.softLimit.reverseSoftLimit(0);
        beltMotorConfig.softLimit.reverseSoftLimitEnabled(false);
        beltMotorConfig.idleMode(IdleMode.kCoast);
        beltMotorConfig.openLoopRampRate(0.15);
        //beltMotorConfig.limitSwitch.forwardLimitSwitchEnabled(false);
        //beltMotorConfig.limitSwitch.reverseLimitSwitchEnabled(false);

        beltMotorConfig.closedLoop.maxOutput(1.0);
        beltMotorConfig.closedLoop.minOutput(-1.0);

        beltMotorConfig.closedLoopRampRate(0.15);
        beltMotorConfig.voltageCompensation(9.0);
        //// Down / outVelocity Values
        // beltMotorConfig.closedLoop.maxMotion.maxAcceleration(5000, beltMotor_CLOSED_LOOP_SLOT_DOWN);
        // beltMotorConfig.closedLoop.maxMotion.maxVelocity(5000, beltMotor_CLOSED_LOOP_SLOT_DOWN);
        // beltMotorConfig.closedLoop.maxMotion.allowedClosedLoopError(beltMotorPosTol, beltMotor_CLOSED_LOOP_SLOT_DOWN);
        // beltMotorConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, beltMotor_CLOSED_LOOP_SLOT_DOWN);

        // //// Up / in Velocity Values
        // beltMotorConfig.closedLoop.maxMotion.maxAcceleration(5000, beltMotor_CLOSED_LOOP_SLOT_UP);
        // beltMotorConfig.closedLoop.maxMotion.maxVelocity(2000, beltMotor_CLOSED_LOOP_SLOT_UP);
        // beltMotorConfig.closedLoop.maxMotion.allowedClosedLoopError(beltMotorPosTol, beltMotor_CLOSED_LOOP_SLOT_UP);
        // beltMotorConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, beltMotor_CLOSED_LOOP_SLOT_UP);

        beltMotorConfig.closedLoop.feedbackSensor(FeedbackSensor.kPrimaryEncoder);

        // config.smartCurrentLimit(50);
        //beltMotorConfig.smartCurrentLimit(normalStallCurrentLimit, normalFreeCurrentLimit);

        //beltMotor.configure(beltMotorConfig, ResetMode.kResetSafeParameters, PersistMode.kPersistParameters);

    }

}

