// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.Constants.CanIds;
import frc.robot.commands.*;

import com.revrobotics.spark.SparkMax;
import com.revrobotics.spark.config.AbsoluteEncoderConfig;
import com.revrobotics.spark.config.SparkBaseConfig.IdleMode;
import com.revrobotics.spark.config.SparkMaxConfig;
import javax.lang.model.util.ElementScanner14;

import org.dyn4j.collision.broadphase.AABBProducer;

import com.revrobotics.spark.ClosedLoopSlot;
import com.revrobotics.spark.FeedbackSensor;
import com.revrobotics.spark.SparkBase.ControlType;
import com.revrobotics.PersistMode;
import com.revrobotics.spark.SparkLowLevel.MotorType;
import com.revrobotics.ResetMode;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Intake extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final double MaxRpm = 0;

    private SparkMax intakeMotor = new SparkMax(CanIds.MOTORS.INTAKE_MOTOR.canId, MotorType.kBrushless);
    private SparkMax extendMotor = new SparkMax(CanIds.MOTORS.EXTEND_MOTOR.canId, MotorType.kBrushless);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private STATUS status = STATUS.RETRACTED;
    private STATUS targetStatus = STATUS.RETRACTED;
    private boolean bIntakeMotorRunning = false;
    private final double posTol = 2.0;
    private boolean bCommandComplete = true;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private SparkMaxConfig intakeConfig = new SparkMaxConfig();
    private SparkMaxConfig extendConfig = new SparkMaxConfig();
    /**
    *
    */
    public Intake() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        if (!bCommandComplete) {
           
        
        switch (status) {
            case RETRACTING:
            if (DriverAssist.isInRange(extendMotor.getEncoder().getPosition(),status.position ,posTol)) {

                status = targetStatus;     

            }

                
                break;
            case EXTENDING:
            if (DriverAssist.isInRange(extendMotor.getEncoder().getPosition(),status.position ,posTol)) {
                if (!bIntakeMotorRunning) {
                    intakeMotor.setVoltage(status.getSpeed());
                    bIntakeMotorRunning = true;
                    status = targetStatus;
                }  
                
            }
            break;
            case EXTENDED_STOPPED:
            if (DriverAssist.isInRange(extendMotor.getEncoder().getPosition(),status.position ,posTol)) {
                //do nothing
                bCommandComplete = true;
            }
                break;
            case EXTENDED_INTAKING:
            if (DriverAssist.isInRange(extendMotor.getEncoder().getPosition(),status.position ,posTol)) {
                //start intake motor
                intakeMotor.setVoltage(status.getSpeed());
                bIntakeMotorRunning = true;
                bCommandComplete = true;
            }
                break;
            case EXTENDED_OUTPUT:
            if (DriverAssist.isInRange(extendMotor.getEncoder().getPosition(),status.position ,posTol)) {
                //start intake motor
                intakeMotor.setVoltage(status.getSpeed());
                bIntakeMotorRunning = true;
                bCommandComplete = true;
            }
                break;
                case RETRACTED:
                if (DriverAssist.isInRange(extendMotor.getEncoder().getPosition(),status.position ,posTol)) {
                //stop intake motor
               // intakeMotor.setVoltage(status.getSpeed());
                bCommandComplete = true;
               
            }
                break;

        
            default:
                break;
        }
    }

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }
    private void setExtendMotorPosition(double position) {
        extendMotor.getClosedLoopController().setSetpoint(position,ControlType.kMAXMotionPositionControl);
    }

    public STATUS getStatus() {
        return status;
    }

    public void setStatus(STATUS status) {
        bCommandComplete = false;
        switch (status) {
            case RETRACTED:
            targetStatus = STATUS.RETRACTED;
            status = STATUS.RETRACTING;
            //set extend motor to retract
            setExtendMotorPosition(status.getPosition());
             intakeMotor.setVoltage(0);
             bIntakeMotorRunning = false;
                break;
            case EXTENDING: //transition state
            targetStatus = STATUS.EXTENDED_STOPPED;
            setExtendMotorPosition(status.getPosition());
             intakeMotor.setVoltage(0);
             bIntakeMotorRunning = false;
                break;
            case RETRACTING://transition state
            targetStatus = STATUS.RETRACTED;    
            setExtendMotorPosition(status.getPosition());
            intakeMotor.setVoltage(0);
                bIntakeMotorRunning = false;
        
                break;
            case EXTENDED_STOPPED:
            targetStatus = STATUS.EXTENDED_STOPPED;
            status = STATUS.EXTENDING;
            setExtendMotorPosition(status.getPosition());
             intakeMotor.setVoltage(0);
             bIntakeMotorRunning = false;
                break;
            case EXTENDED_INTAKING:
            targetStatus = STATUS.EXTENDED_INTAKING;
            status = STATUS.EXTENDING;
            setExtendMotorPosition(status.getPosition());
             intakeMotor.setVoltage(0);
             bIntakeMotorRunning = false;

                break;
            case EXTENDED_OUTPUT:
            targetStatus = STATUS.EXTENDED_OUTPUT;
            status = STATUS.EXTENDING;
            setExtendMotorPosition(status.getPosition());
             intakeMotor.setVoltage(0);
                bIntakeMotorRunning = false;
                break;  
        
            default:
            targetStatus = STATUS.RETRACTED;
            status = STATUS.RETRACTING;
             intakeMotor.setVoltage(0);
                bIntakeMotorRunning = false;
                 setExtendMotorPosition(STATUS.RETRACTING.getPosition());
                break;
        }
        this.status = status;
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    private void configintakeMotor() {


        // config.encoder.positionConversionFactor(Math.PI * elevator_gearDiameter /
        // elevator_gearRatio);
        intakeConfig.encoder.positionConversionFactor(1);
        intakeConfig.inverted(true);
        intakeConfig.softLimit.forwardSoftLimitEnabled(false);
        intakeConfig.softLimit.reverseSoftLimit(0);
        intakeConfig.softLimit.reverseSoftLimitEnabled(false);
        intakeConfig.idleMode(IdleMode.kCoast);
        intakeConfig.openLoopRampRate(0.15);
        //intakeConfig.limitSwitch.forwardLimitSwitchEnabled(false);
        //intakeConfig.limitSwitch.reverseLimitSwitchEnabled(false);

        intakeConfig.closedLoop.maxOutput(1.0);
        intakeConfig.closedLoop.minOutput(-1.0);

        intakeConfig.closedLoopRampRate(0.15);
        intakeConfig.voltageCompensation(9.0);
        //// Down / outVelocity Values
        // intakeConfig.closedLoop.maxMotion.maxAcceleration(5000, rTowerR_CLOSED_LOOP_SLOT_DOWN);
        // intakeConfig.closedLoop.maxMotion.maxVelocity(5000, rTowerR_CLOSED_LOOP_SLOT_DOWN);
        // intakeConfig.closedLoop.maxMotion.allowedClosedLoopError(rTowerRPosTol, rTowerR_CLOSED_LOOP_SLOT_DOWN);
        // intakeConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rTowerR_CLOSED_LOOP_SLOT_DOWN);

        // //// Up / in Velocity Values
        // intakeConfig.closedLoop.maxMotion.maxAcceleration(5000, rTowerR_CLOSED_LOOP_SLOT_UP);
        // intakeConfig.closedLoop.maxMotion.maxVelocity(2000, rTowerR_CLOSED_LOOP_SLOT_UP);
        // intakeConfig.closedLoop.maxMotion.allowedClosedLoopError(rTowerRPosTol, rTowerR_CLOSED_LOOP_SLOT_UP);
        // intakeConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rTowerR_CLOSED_LOOP_SLOT_UP);

        intakeConfig.closedLoop.feedbackSensor(FeedbackSensor.kPrimaryEncoder);

        // config.smartCurrentLimit(50);
        //intakeConfig.smartCurrentLimit(normalStallCurrentLimit, normalFreeCurrentLimit);

        //intakeMotor.configure(intakeConfig, ResetMode.kResetSafeParameters, PersistMode.kPersistParameters);

    }

    private void configextendMotor() {


        // config.encoder.positionConversionFactor(Math.PI * elevator_gearDiameter /
        // elevator_gearRatio);
        extendConfig.encoder.positionConversionFactor(1);
        extendConfig.inverted(true);
        extendConfig.softLimit.forwardSoftLimitEnabled(false);
        extendConfig.softLimit.reverseSoftLimit(0);
        extendConfig.softLimit.reverseSoftLimitEnabled(false);
        extendConfig.idleMode(IdleMode.kCoast);
        extendConfig.openLoopRampRate(0.15);
        //extendConfig.limitSwitch.forwardLimitSwitchEnabled(false);
        //extendConfig.limitSwitch.reverseLimitSwitchEnabled(false);

        extendConfig.closedLoop.maxOutput(1.0);
        extendConfig.closedLoop.minOutput(-1.0);
        extendConfig.closedLoopRampRate(0.15);
        extendConfig.voltageCompensation(9.0);
        //// Down / outVelocity Values
        // extendConfig.closedLoop.maxMotion.maxAcceleration(5000, rTowerL_CLOSED_LOOP_SLOT_DOWN);
        // extendConfig.closedLoop.maxMotion.maxVelocity(5000, rTowerL_CLOSED_LOOP_SLOT_DOWN);
        // extendConfig.closedLoop.maxMotion.allowedClosedLoopError(rTowerLPosTol, rTowerL_CLOSED_LOOP_SLOT_DOWN);
        // extendConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rTowerL_CLOSED_LOOP_SLOT_DOWN);

        // //// Up / in Velocity Values
        // extendConfig.closedLoop.maxMotion.maxAcceleration(5000, rTowerL_CLOSED_LOOP_SLOT_UP);
        // extendConfig.closedLoop.maxMotion.maxVelocity(2000, rTowerL_CLOSED_LOOP_SLOT_UP);
        // extendConfig.closedLoop.maxMotion.allowedClosedLoopError(rTowerLPosTol, rTowerL_CLOSED_LOOP_SLOT_UP);
        // extendConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rTowerL_CLOSED_LOOP_SLOT_UP);

        extendConfig.closedLoop.feedbackSensor(FeedbackSensor.kPrimaryEncoder);
        AbsoluteEncoderConfig absEncConfig = new AbsoluteEncoderConfig();
        //absEncConfig.zeroOffset(0.649);
        absEncConfig.inverted(false);
        absEncConfig.positionConversionFactor(360);

        extendConfig.absoluteEncoder.apply(absEncConfig);

        // config.smartCurrentLimit(50);
        //extendConfig.smartCurrentLimit(normalStallCurrentLimit, normalFreeCurrentLimit);

        extendMotor.configure(extendConfig, ResetMode.kResetSafeParameters, PersistMode.kPersistParameters);

    }

        // Enumeration of status which should store position and speed values
    public enum STATUS {
        RETRACTED(90.0, 0.0),
        RETRACTING(0.0, 0.0),
        EXTENDED_STOPPED(0.0, 0.0),
        EXTENDING(0.0, 0.0),
        EXTENDED_INTAKING(0.0, 0.0), 
        EXTENDED_OUTPUT(0.0, 0.0);

        private final double position;
        private final double speed; //in volts

        STATUS(double position, double speed) { 
            this.position = position;
            this.speed = speed;
        }
        public double getPosition() {
            return position;
        }
        public double getSpeed() {
            return speed;
        }
    }

}