// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants.CanIds;
import frc.robot.RobotContainer;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Launcher extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    public LFlywheels flywheels_LH;
    public LFlywheels flywheels_RH;
    public LTurret turret;
    private Pose2d targetPose = new Pose2d(1, 4, new Rotation2d(0));
    private LauncherStatus status = LauncherStatus.STOPPED;
    private String combinedStatus = "Initializing";
    private Pose2d currentPose = new Pose2d(1, 4, new Rotation2d(0));
    private double distanceToTarget;
    private double targetAngle;

    private double autoOffsetRPM = 0;
    private double autioffsetAim = 0;
    private double currentAngle;
    private boolean bActive = true;
    private boolean bRHF_Enabled = true;
    private boolean bLHF_Enabled = true;
    private boolean bturret_Enabled = true;
    private boolean bShotCalc = false;
    private double[] pidFlyWheelLH1 = { 0.00040, 0.0, 0.00000001, 0.00182 }; // 9 tower 2 right p was 0.00037
    private double[] pidFlyWheelLH2 = { 0.00040, 0.0, 0.00000001, 0.001821 }; // 18 tower 2 left
    private double[] pidFlyWheelRH1 = { 0.00040, 0.0, 0.00000001, 0.001822 }; // 11 tower 1 right
    private double[] pidFlyWheelRH2 = { 0.00040, 0.0, 0.00000001, 0.001823 }; // 12 tower 1 left

    private boolean bAutoAngle = false;

    private LinearCalc shotCalc = new LinearCalc();
    private LinearCalc turretCalc = new LinearCalc();

    private double targetRPM;
    private double FieldDistanceOffSet = -5.0;  // in inches

    public static final double TURRET_OFFSET_X = -0.2; // 20 cm back from robot center
    public static final double TURRET_OFFSET_Y = 0.0; // centered left-right

    private double flywheelSpeed;

    private final double baselineDistanceInches = 131.0;
    private final double baselineRPM = 3337.0;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
    *
    */
    public Launcher() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        flywheels_LH = new LFlywheels(CanIds.MOTORS.TOWER1_MOTOR_RIGHT.canId,
                CanIds.MOTORS.TOWER1_MOTOR_LEFT.canId, pidFlyWheelLH1, pidFlyWheelLH2);
        flywheels_RH = new LFlywheels(CanIds.MOTORS.TOWER2_MOTOR_RIGHT.canId,
                CanIds.MOTORS.TOWER2_MOTOR_LEFT.canId, pidFlyWheelRH1, pidFlyWheelRH2);
        turret = new LTurret();

        //shotCalc.add(new LinearCalcRef(3337, 131, edu.wpi.first.units.Units.Inches));  unnecessary point
        shotCalc.add(new LinearCalcRef(3470, 114.5, edu.wpi.first.units.Units.Inches));
        shotCalc.add(new LinearCalcRef(3520, 132, edu.wpi.first.units.Units.Inches));
        shotCalc.add(new LinearCalcRef(3650, 145, edu.wpi.first.units.Units.Inches));
        shotCalc.add(new LinearCalcRef(3815, 156, edu.wpi.first.units.Units.Inches));
        shotCalc.add(new LinearCalcRef(4056, 167, edu.wpi.first.units.Units.Inches));
        shotCalc.Calculate();

        shotCalc.setMinimumRPM(1800);

        turretCalc.add(new LinearCalcRef(0, 0, edu.wpi.first.units.Units.Degrees));
        turretCalc.add(new LinearCalcRef(250, 45, edu.wpi.first.units.Units.Degrees));
        turretCalc.add(new LinearCalcRef(779, 100, edu.wpi.first.units.Units.Degrees));
        turretCalc.add(new LinearCalcRef(812, 135, edu.wpi.first.units.Units.Degrees));
        turretCalc.add(new LinearCalcRef(846, 180, edu.wpi.first.units.Units.Degrees));
        turretCalc.add(new LinearCalcRef(812, 225, edu.wpi.first.units.Units.Degrees));
        turretCalc.add(new LinearCalcRef(779, 260, edu.wpi.first.units.Units.Degrees));
        turretCalc.add(new LinearCalcRef(250, 315, edu.wpi.first.units.Units.Degrees));
        turretCalc.add(new LinearCalcRef(0, 360, edu.wpi.first.units.Units.Degrees));
        turretCalc.Calculate();


    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        if (turret == null || flywheels_LH == null || flywheels_RH == null) {
            combinedStatus = " ...Startin' up... T " + (turret == null) + " FL " + (flywheels_LH == null) + " FR "
                    + (flywheels_RH == null);
        } else {
            // calculate combined status values from each sub component
            combinedStatus = status.toString() + " T " + turret.getStatus().toString() + " L "
                    + flywheels_LH.getStatus().toString() + " R " + flywheels_RH.getStatus().toString();
            currentAngle = turret.getCurrAngle();

        }
        // update current robot pose from drivetrain odometry
        currentPose = RobotContainer.getInstance().m_driveTrain.getPose();
         UpdateTurretPose(); //compensating for turret position
        if (bActive) {

            // calculate distance and angle to target

            // calcDistanceToTarget();
            if (bAutoAngle) {
                if (bturret_Enabled) {
                    targetAngle = getRelativeAngleToTarget() + autioffsetAim;
                } else {
                    targetAngle = getAngleToTarget();
                    RobotContainer.getInstance().m_driveTrain.THeading = targetAngle;
                }
            } else {
                // set static angle

            }

            // set rpm based on distance to target

            if (bShotCalc) {
                calcDistanceToTarget();
                targetRPM = shotCalc.getRPM(distanceToTarget) + turretCalc.getRPM(targetAngle) + autoOffsetRPM;
                // targetRPM = getTargetRPM(distanceToTarget, targetAngle) + autoOffsetRPM; // testing new method
            }
            // insert calcuation for shoot on the fly
            //shootOnTheFly();

            // once we define turret zones we may have to adujust RPM based on angle to
            // target

            // set final values to flywheel and turret
            if (bLHF_Enabled == true) {
                flywheels_LH.setRPM(targetRPM);
            } else {
                flywheels_LH.setRPM(0);
            }

            if (bRHF_Enabled == true) {
                flywheels_RH.setRPM(targetRPM);
            } else {
                flywheels_RH.setRPM(0);
            }

            if (bturret_Enabled == true) {
                turret.setAngle(targetAngle);
            } else {
                // do nothing
            }

        } else {

        }

        switch (status) {
            case READY_TO_FIRE:
                // Handle ready to fire logic
                break;
            case ACQUIRING_TARGETING:
                // Handle targeting logic
                break;
            case IDLE:
                // Handle idle logic
                break;
            case STOPPED:
                // Handle stopped logic
                break;

            default:
                break;
        }

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    public void setNewTarget(Pose2d target) {
        this.targetPose = target;
    }

    public Pose2d getTargetPose() {
        return this.targetPose;
    }

    public String getCombinedStatus() {
        return combinedStatus;
    }

    public LauncherStatus getStatus() {
        return status;
    }

    private void calcDistanceToTarget() {
        distanceToTarget = (DriverAssist.getDistanceToTarget(currentPose, targetPose.getTranslation()) * 39.37) + FieldDistanceOffSet; // meters
                                                                                                               // to
                                                                                                               // inches
    }
    public double getDistanceToTarget(){
        return (DriverAssist.getDistanceToTarget(currentPose, targetPose.getTranslation()) * 39.37) + FieldDistanceOffSet;
    }

    public double getAngleToTarget() {
        return DriverAssist.getAngleToTarget(currentPose, targetPose.getTranslation()).getDegrees();
    }

    public void UpdateTurretPose() {
        // Given:
        // Pose2d robotPose; // field-relative robot pose
        // Rotation2d turretAngleRobot; // turret angle relative to robot frame
        Translation2d turretOffsetRobot = new Translation2d(
                -0.20625,
                0.0);

        Translation2d turretOffsetField = turretOffsetRobot.rotateBy(currentPose.getRotation());

        // Step 2: compute turret position in field frame
        Translation2d turretPositionField = currentPose.getTranslation()
                .plus(turretOffsetField);

        // Step 3: compute turret heading in field frame
        Rotation2d turretHeadingField = currentPose.getRotation();//plus(new Rotation2d(currentAngle));

        // Final turret pose in field coordinates
        currentPose = new Pose2d(
                turretPositionField,
                turretHeadingField);

    }

    public double getRelativeAngleToTarget() {
        /*
         * if(RobotContainer.getInstance().m_fmsSystem.getAlliance() == Alliance.Blue) {
         * return DriverAssist.getRelativeAngleToTarget(currentPose,
         * targetPose.getTranslation()).getDegrees() +180;
         * }
         * else {
         * return DriverAssist.getRelativeAngleToTarget(currentPose,
         * targetPose.getTranslation()).getDegrees();
         *
         *
         * }
         */
        return targetPose.getTranslation().minus(currentPose.getTranslation()).getAngle()
                .minus(new Rotation2d(currentPose.getRotation().getRadians())).getDegrees();

        // return DriverAssist.getRelativeAngleToTarget(currentPose,
        // targetPose.getTranslation()).getDegrees();

    }

    public boolean getbLHF_Enabled() {
        return bLHF_Enabled;
    }

    public void setTargetRPM(double newRPM, boolean auto) {
        targetRPM = newRPM;
        bShotCalc = auto;
    }

    public boolean getBShotCalc() {
        return bShotCalc;
    }

    public void setAngle(double newAngle, boolean Auto) {
        targetAngle = newAngle;
        if (newAngle == -1) {
            bAutoAngle = true;

        } else {
            bAutoAngle = false;
        }

    }

    public void enableTurret(boolean enable) {
        bturret_Enabled = enable;
    }

    public boolean getTurretStatus() {
        return bturret_Enabled;
    }

    public void addRPM() {
        if (bShotCalc) {
            autoOffsetRPM = autoOffsetRPM + 25;
        } else {
            targetRPM = targetRPM + 50;
        }
    }

    public double getautioffsetAim() {
        return autioffsetAim;
    }

    public void addAimoffset() {
        autioffsetAim = autioffsetAim + 2;
    }

    public void minusAimoffSet() {
        autioffsetAim = autioffsetAim - 2;
    }

    public void minusRPM() {
        if (bShotCalc) {
            autoOffsetRPM = autoOffsetRPM - 25;
        } else {
            targetRPM = targetRPM - 50;
        }
    }

    public void resetRPM() {
        autoOffsetRPM = 0;
    }

    public double getTargetRPM() {
        return targetRPM;
    }

    public boolean getbRHF_Enabled() {
        return bRHF_Enabled;
    }

    public void setbLHF_Enabled(boolean bLHF_E) {
        this.bLHF_Enabled = bLHF_E;
    }

    public void setbRHF_Enabled(boolean bRHF_E) {
        this.bRHF_Enabled = bRHF_E;
    }

    public double getAutoOffSetARPM() {
        return autoOffsetRPM;
    }

    public void setAutoOffSetRPM(double newOffset) {
        autoOffsetRPM = autoOffsetRPM + newOffset;
    }

    public void setStatus(LauncherStatus newStatus) {

        switch (newStatus) {

            case ACQUIRING_TARGETING:
                bActive = true;
                break;

            case IDLE:
                bActive = false;
                break;
            case STOPPED:
                bActive = false;
                break;
            default:
                newStatus = LauncherStatus.ACQUIRING_TARGETING;
                bActive = true;
                break;
        }
        this.status = newStatus;
    }

    public double getTargetRPM(double distanceInches, double turretAngleDegrees) {

        // Distance scaling: +1% per inch farther than baseline
        double deltaInches = distanceInches - baselineDistanceInches;
        double distanceScale = 1.0 + (0.01 * deltaInches);

        // Angle correction: 0–135° → 0%, 135–180° → +15%
        double a = Math.abs(turretAngleDegrees);
        double angleScale = ((a > 135.0) && (a < 225.0)) ? 1.15 : 1.0;

        // Final RPM
        return baselineRPM * distanceScale * angleScale;
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    // need to create enum for status of launcher READY_TO_FUEL, NOT_READY.
    public enum LauncherStatus {
        READY_TO_FIRE,
        ACQUIRING_TARGETING,
        IDLE,
        STOPPED;
    }

    private void shootOnTheFly() {
        double vxMPS = RobotContainer.getInstance().m_driveTrain.getSwerveDrive().getRobotVelocity().vxMetersPerSecond;
        double vyMPS = RobotContainer.getInstance().m_driveTrain.getSwerveDrive().getRobotVelocity().vyMetersPerSecond;

        double latency = 0.150; // Tuned constant
        Translation2d futurePos = currentPose.getTranslation().plus(
                new Translation2d(vxMPS, vyMPS).times(latency));

        // 2. GET TARGET VECTOR
        Translation2d goalLocation = targetPose.getTranslation();
        Translation2d targetVec = goalLocation.minus(futurePos);
        double dist = targetVec.getNorm();

        // 3. CALCULATE IDEAL SHOT (Stationary)
        // Note: This returns HORIZONTAL velocity component
        // Gear ratio should include ratio of motor to gears to wheels
        // Times wheel diameter times pi.
        double wheelDiameter = 0.0635;  //in metersd
        double gearRatio = 1.5;
        double totalRatio = gearRatio * wheelDiameter * Math.PI;
         // Placeholder: Convert RPM to m/s based on your shooter characteristics
        double idealHorizontalSpeed = (targetRPM * totalRatio) * Math.cos(Math.toRadians(54.314));

        // 4. VECTOR SUBTRACTION
        Translation2d robotVelVec = new Translation2d(vxMPS, vyMPS);
        Translation2d shotVec = targetVec.div(dist).times(idealHorizontalSpeed).minus(robotVelVec);

        // 5. CONVERT TO CONTROLS
        targetAngle = shotVec.getAngle().getDegrees();
        //targetRPM = shotVec.getNorm(); // convert back to RPM based on your shooter characteristics, still need to verify

        targetRPM = shotCalc.getRPM((shotVec.getNorm() * 39.37)) + turretCalc.getRPM(targetAngle) + autoOffsetRPM;
        // targetRPM = getTargetRPM((shotVec.getNorm() * 39.37), targetAngle) + autoOffsetRPM;


        // 6. SOLVE FOR NEW PITCH/RPM
        // Assuming constant total exit velocity, variable hood:
        // double totalExitVelocity = 15.0; // m/s
        // Clamp to avoid domain errors if we need more speed than possible
        // double ratio = Math.min(targetRPM / totalExitVelocity, 1.0);
        // double newPitch = Math.acos(ratio);

        // 7. SET OUTPUTS
        // turret.setAngle(turretAngle);
        // hood.setAngle(Math.toDegrees(newPitch));
        // shooter.setRPM(calcRPM(totalExitVelocity));

    }

    // need to create enum for known targets RED_HUB, BLUE_HUB, RED_DEPOT,
    // BLUE_DEPOT, RED_OUTPOST, BLUE_OUTPOST
    // for each enum entry we need to store name, pose2d, "type"
    public enum KnownTargets {
        RED_HUB("Red Hub",
                new edu.wpi.first.math.geometry.Pose2d(11.917, 4.030, new edu.wpi.first.math.geometry.Rotation2d(0)),
                "Hub", Alliance.Red),
        BLUE_HUB("Blue Hub",
                new edu.wpi.first.math.geometry.Pose2d(5.123, 4.030, new edu.wpi.first.math.geometry.Rotation2d(0)),
                "Hub", Alliance.Blue),
        RED_DEPOT("Red Depot",
                new edu.wpi.first.math.geometry.Pose2d(15.877, 1.135, new edu.wpi.first.math.geometry.Rotation2d(0)),
                "Depot", Alliance.Red),
        BLUE_DEPOT("Blue Depot",
                new edu.wpi.first.math.geometry.Pose2d(0.792, 6.967, new edu.wpi.first.math.geometry.Rotation2d(0)),
                "Depot", Alliance.Blue),
        RED_OUTPOST("Red Outpost",
                new edu.wpi.first.math.geometry.Pose2d(15.963, 6.902, new edu.wpi.first.math.geometry.Rotation2d(0)),
                "Outpost", Alliance.Red),
        BLUE_OUTPOST("Blue Outpost",
                new edu.wpi.first.math.geometry.Pose2d(0.534, 1.135, new edu.wpi.first.math.geometry.Rotation2d(0)),
                "Outpost", Alliance.Blue),
        BLUE_CENTERTARGET("Blue Center Target",
                new edu.wpi.first.math.geometry.Pose2d(2.706, 1.618, new edu.wpi.first.math.geometry.Rotation2d(0)),
                "Center Target", Alliance.Blue),
        RED_CENTERTARGET("Red Center Target",
                new edu.wpi.first.math.geometry.Pose2d(14.220, 5.461, new edu.wpi.first.math.geometry.Rotation2d(0)),
                "Center Target", Alliance.Red);

        // Store name, pose2d, and "type" for each target
        private final String name;
        private final edu.wpi.first.math.geometry.Pose2d pose2d;
        private final String type;
        private final Alliance alliance;

        KnownTargets(String name, edu.wpi.first.math.geometry.Pose2d pose2d, String type, Alliance alliance) {
            this.name = name;
            this.pose2d = pose2d;
            this.type = type;
            this.alliance = alliance;
        }

        public String getName() {
            return name;
        }

        public edu.wpi.first.math.geometry.Pose2d getPose2d() {
            return pose2d;
        }

        public String getType() {
            return type;
        }
    }
}