// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.Constants.CanIds;
import frc.robot.commands.*;

import com.revrobotics.spark.SparkMax;
import com.revrobotics.spark.config.SparkBaseConfig.IdleMode;
import com.revrobotics.spark.config.SparkMaxConfig;
import javax.lang.model.util.ElementScanner14;
import com.revrobotics.spark.ClosedLoopSlot;
import com.revrobotics.spark.FeedbackSensor;
import com.revrobotics.spark.SparkBase.ControlType;
import com.revrobotics.spark.SparkBase.PersistMode;
import com.revrobotics.spark.SparkLowLevel.MotorType;
import com.revrobotics.spark.SparkBase.ResetMode;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class LFlywheels extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final double MaxRpm = 0;

    private SparkMax TowerRM;
    private SparkMax TowerLM;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final double Start = 1.0;
    private final double Stop = 0.0;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private SparkMaxConfig rTowerRConfig = new SparkMaxConfig();
    private SparkMaxConfig rTowerLConfig = new SparkMaxConfig();
    /**
    *
    */
    public LFlywheels(int TowerMotorR_canid, int TowerMotorL_canid) {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        TowerRM = new SparkMax(TowerMotorR_canid, MotorType.kBrushless);
        TowerLM = new SparkMax(TowerMotorL_canid, MotorType.kBrushless);
        configrTowerRMotor();
        configrTowerLMotor();
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    private void configrTowerRMotor() {


        // config.encoder.positionConversionFactor(Math.PI * elevator_gearDiameter /
        // elevator_gearRatio);
        rTowerRConfig.encoder.positionConversionFactor(1);
        rTowerRConfig.inverted(true);
        rTowerRConfig.softLimit.forwardSoftLimitEnabled(false);
        rTowerRConfig.softLimit.reverseSoftLimit(0);
        rTowerRConfig.softLimit.reverseSoftLimitEnabled(false);
        rTowerRConfig.idleMode(IdleMode.kCoast);
        rTowerRConfig.openLoopRampRate(0.15);
        //rTowerRConfig.limitSwitch.forwardLimitSwitchEnabled(false);
        //rTowerRConfig.limitSwitch.reverseLimitSwitchEnabled(false);

        rTowerRConfig.closedLoop.maxOutput(1.0);
        rTowerRConfig.closedLoop.minOutput(-1.0);

        rTowerRConfig.closedLoopRampRate(0.15);
        rTowerRConfig.voltageCompensation(9.0);
        //// Down / outVelocity Values
        // rTowerRConfig.closedLoop.maxMotion.maxAcceleration(5000, rTowerR_CLOSED_LOOP_SLOT_DOWN);
        // rTowerRConfig.closedLoop.maxMotion.maxVelocity(5000, rTowerR_CLOSED_LOOP_SLOT_DOWN);
        // rTowerRConfig.closedLoop.maxMotion.allowedClosedLoopError(rTowerRPosTol, rTowerR_CLOSED_LOOP_SLOT_DOWN);
        // rTowerRConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rTowerR_CLOSED_LOOP_SLOT_DOWN);

        // //// Up / in Velocity Values
        // rTowerRConfig.closedLoop.maxMotion.maxAcceleration(5000, rTowerR_CLOSED_LOOP_SLOT_UP);
        // rTowerRConfig.closedLoop.maxMotion.maxVelocity(2000, rTowerR_CLOSED_LOOP_SLOT_UP);
        // rTowerRConfig.closedLoop.maxMotion.allowedClosedLoopError(rTowerRPosTol, rTowerR_CLOSED_LOOP_SLOT_UP);
        // rTowerRConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rTowerR_CLOSED_LOOP_SLOT_UP);

        rTowerRConfig.closedLoop.feedbackSensor(FeedbackSensor.kPrimaryEncoder);

        // config.smartCurrentLimit(50);
        //rTowerRConfig.smartCurrentLimit(normalStallCurrentLimit, normalFreeCurrentLimit);

        //rTowerRMotor.configure(rTowerRConfig, ResetMode.kResetSafeParameters, PersistMode.kPersistParameters);

    }

    private void configrTowerLMotor() {


        // config.encoder.positionConversionFactor(Math.PI * elevator_gearDiameter /
        // elevator_gearRatio);
        rTowerLConfig.encoder.positionConversionFactor(1);
        rTowerLConfig.inverted(true);
        rTowerLConfig.softLimit.forwardSoftLimitEnabled(false);
        rTowerLConfig.softLimit.reverseSoftLimit(0);
        rTowerLConfig.softLimit.reverseSoftLimitEnabled(false);
        rTowerLConfig.idleMode(IdleMode.kCoast);
        rTowerLConfig.openLoopRampRate(0.15);
        //rTowerLConfig.limitSwitch.forwardLimitSwitchEnabled(false);
        //rTowerLConfig.limitSwitch.reverseLimitSwitchEnabled(false);

        rTowerLConfig.closedLoop.maxOutput(1.0);
        rTowerLConfig.closedLoop.minOutput(-1.0);
        rTowerLConfig.closedLoopRampRate(0.15);
        rTowerLConfig.voltageCompensation(9.0);
        //// Down / outVelocity Values
        // rTowerLConfig.closedLoop.maxMotion.maxAcceleration(5000, rTowerL_CLOSED_LOOP_SLOT_DOWN);
        // rTowerLConfig.closedLoop.maxMotion.maxVelocity(5000, rTowerL_CLOSED_LOOP_SLOT_DOWN);
        // rTowerLConfig.closedLoop.maxMotion.allowedClosedLoopError(rTowerLPosTol, rTowerL_CLOSED_LOOP_SLOT_DOWN);
        // rTowerLConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rTowerL_CLOSED_LOOP_SLOT_DOWN);

        // //// Up / in Velocity Values
        // rTowerLConfig.closedLoop.maxMotion.maxAcceleration(5000, rTowerL_CLOSED_LOOP_SLOT_UP);
        // rTowerLConfig.closedLoop.maxMotion.maxVelocity(2000, rTowerL_CLOSED_LOOP_SLOT_UP);
        // rTowerLConfig.closedLoop.maxMotion.allowedClosedLoopError(rTowerLPosTol, rTowerL_CLOSED_LOOP_SLOT_UP);
        // rTowerLConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rTowerL_CLOSED_LOOP_SLOT_UP);

        rTowerLConfig.closedLoop.feedbackSensor(FeedbackSensor.kPrimaryEncoder);

        // config.smartCurrentLimit(50);
        //rTowerLConfig.smartCurrentLimit(normalStallCurrentLimit, normalFreeCurrentLimit);

        //rTowerLMotor.configure(rTowerLConfig, ResetMode.kResetSafeParameters, PersistMode.kPersistParameters);

    }

}

