// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.Constants.CanIds;
import frc.robot.commands.*;

import com.revrobotics.spark.SparkMax;
import com.revrobotics.spark.config.SparkBaseConfig.IdleMode;
import com.revrobotics.spark.config.SparkMaxConfig;

import java.lang.annotation.Target;

import javax.lang.model.util.ElementScanner14;
import com.revrobotics.spark.ClosedLoopSlot;
import com.revrobotics.spark.FeedbackSensor;
import com.revrobotics.spark.SparkBase.ControlType;
import com.revrobotics.spark.SparkBase.PersistMode;
import com.revrobotics.spark.SparkLowLevel.MotorType;
import com.revrobotics.spark.SparkBase.ResetMode;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class LFlywheels extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final double MaxRpm = 0;

    private SparkMax TowerRM;
    private SparkMax TowerLM;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private double TargetRPM = 0.0;
    private FlywheelStatus status = FlywheelStatus.STOPPED;
    private final double RPM_Tolerance = 20.0;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private SparkMaxConfig TowerConfig = new SparkMaxConfig();
    
    /**
    *
    */
    public LFlywheels(int TowerMotorR_canid, int TowerMotorL_canid) {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        TowerRM = new SparkMax(TowerMotorR_canid, MotorType.kBrushless);
        TowerLM = new SparkMax(TowerMotorL_canid, MotorType.kBrushless);
        configrTowerMotor(TowerRM);
        configrTowerMotor(TowerLM);
       
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

        public void setRPM(double rpm) {
        TargetRPM = rpm;
        TowerRM.getClosedLoopController().setSetpoint(rpm, ControlType.kVelocity);
        TowerLM.getClosedLoopController().setSetpoint(rpm, ControlType.kVelocity);
        status = FlywheelStatus.RAMPING;

        }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    private void configrTowerMotor(SparkMax motor) {


        // config.encoder.positionConversionFactor(Math.PI * elevator_gearDiameter /
        // elevator_gearRatio);
        TowerConfig.encoder.positionConversionFactor(1);
        TowerConfig.inverted(true);
        TowerConfig.softLimit.forwardSoftLimitEnabled(false);
        //TowerConfig.softLimit.reverseSoftLimit(0);
        TowerConfig.softLimit.reverseSoftLimitEnabled(false);
        TowerConfig.idleMode(IdleMode.kCoast);
        TowerConfig.openLoopRampRate(0.15);
        //rTowerRConfig.limitSwitch.forwardLimitSwitchEnabled(false);
        //rTowerRConfig.limitSwitch.reverseLimitSwitchEnabled(false);

        TowerConfig.closedLoop.maxOutput(1.0);
        TowerConfig.closedLoop.minOutput(-1.0);

        TowerConfig.closedLoopRampRate(0.15);
        TowerConfig.voltageCompensation(9.0);
        TowerConfig.closedLoop.maxMotion.cruiseVelocity(0);
        //TowerConfig.closedLoop.maxMotion.maxAcceleration(0);
        TowerConfig.closedLoop.pid(0.4, 0.0, 0.0, ClosedLoopSlot.kSlot0);
        //// Down / outVelocity Values
        // TowerConfig.closedLoop.maxMotion.maxAcceleration(5000, TowerConfig_CLOSED_LOOP_SLOT_DOWN);
        // TowerConfig.closedLoop.maxMotion.maxVelocity(5000, TowerConfig_CLOSED_LOOP_SLOT_DOWN);
        // TowerConfig.closedLoop.maxMotion.allowedClosedLoopError(TowerConfigPosTol, TowerConfig_CLOSED_LOOP_SLOT_DOWN);
        // TowerConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, TowerConfig_CLOSED_LOOP_SLOT_DOWN);

        // //// Up / in Velocity Values
        // */ TowerConfig.closedLoop.maxMotion.maxAcceleration(5000, Tower_CLOSED_LOOP_SLOT_UP);
         //TowerConfig.closedLoop.maxMotion.maxVelocity(2000, Tower_CLOSED_LOOP_SLOT_UP);
        // TowerConfig.closedLoop.maxMotion.allowedClosedLoopError(TowerConfigPosTol, Tower_CLOSED_LOOP_SLOT_UP);
        // TowerConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, Tower_CLOSED_LOOP_SLOT_UP);

        TowerConfig.closedLoop.feedbackSensor(FeedbackSensor.kPrimaryEncoder);

        TowerConfig.smartCurrentLimit(50);
        //rTowerRConfig.smartCurrentLimit(normalStallCurrentLimit, normalFreeCurrentLimit);

        //rTowerRMotor.configure(rTowerRConfig, ResetMode.kResetSafeParameters, PersistMode.kPersistParameters);

    }

    //need to create enum for status of flywheels
    public enum FlywheelStatus {
        RAMPING,
        REVERSE,
        AT_SPEED,
        STOPPED;
        
    }
   

}

