// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.Constants.CanIds;
import frc.robot.commands.*;

import com.revrobotics.spark.SparkMax;
import com.revrobotics.spark.config.AbsoluteEncoderConfig;
import com.revrobotics.spark.config.SparkBaseConfig.IdleMode;
import com.revrobotics.spark.config.SparkMaxConfig;
import javax.lang.model.util.ElementScanner14;
import com.revrobotics.spark.ClosedLoopSlot;
import com.revrobotics.spark.FeedbackSensor;
import com.revrobotics.spark.SparkBase.ControlType;
import com.revrobotics.PersistMode;
import com.revrobotics.spark.SparkLowLevel.MotorType;
import com.revrobotics.ResetMode;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class LTurret extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final double MaxRpm = 0;

    private SparkMax turningMotor = new SparkMax(CanIds.MOTORS.TURN_MOTOR.canId, MotorType.kBrushless);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private double TargetAngle = 0.0;
    private TurretStatus status = TurretStatus.STOPPED;
    private final double Angle_Tolerance = 0.5;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private SparkMaxConfig turningConfig = new SparkMaxConfig();
    /**
    *
    */
    public LTurret() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        switch (status) {
            case TARGETING:
                if (DriverAssist.isInRange(getCurrAngle(), TargetAngle, Angle_Tolerance)) {
                        status = TurretStatus.ON_TARGET;
                }
                break;
            case ON_TARGET:
                break;
            case STOPPED:
                break;
        }

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    public double getCurrAngle() {
        return turningMotor.getEncoder().getPosition();
    }

    public void setAngle(double angle) {
        TargetAngle = angle;
        turningMotor.getClosedLoopController().setSetpoint(angle, ControlType.kPosition);
        status = TurretStatus.TARGETING;
    }

    public TurretStatus getStatus() {
        return status;
    }

    public double getTargetAngle() {
        return TargetAngle;
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    private void configTurningMotor() {


        // config.encoder.positionConversionFactor(Math.PI * elevator_gearDiameter /
        // elevator_gearRatio);
        turningConfig.encoder.positionConversionFactor(360);
        turningConfig.inverted(true);
        turningConfig.softLimit.forwardSoftLimitEnabled(false);
        turningConfig.softLimit.reverseSoftLimit(0);
        turningConfig.softLimit.reverseSoftLimitEnabled(false);
        turningConfig.idleMode(IdleMode.kBrake);
        turningConfig.openLoopRampRate(0.15);
        //intakeConfig.limitSwitch.forwardLimitSwitchEnabled(false);
        //intakeConfig.limitSwitch.reverseLimitSwitchEnabled(false);

        turningConfig.closedLoop.maxOutput(1.0);
        turningConfig.closedLoop.minOutput(-1.0);

        turningConfig.closedLoopRampRate(0.15);
        turningConfig.voltageCompensation(9.0);
        //// Down / outVelocity Values
        // turningConfig.closedLoop.maxMotion.maxAcceleration(5000, rTowerR_CLOSED_LOOP_SLOT_DOWN);
        // turningConfig.closedLoop.maxMotion.maxVelocity(5000, rTowerR_CLOSED_LOOP_SLOT_DOWN);
        // turningConfig.closedLoop.maxMotion.allowedClosedLoopError(rTowerRPosTol, rTowerR_CLOSED_LOOP_SLOT_DOWN);
        // turningConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rTowerR_CLOSED_LOOP_SLOT_DOWN);

        // //// Up / in Velocity Values
        // turningConfig.closedLoop.maxMotion.maxAcceleration(5000, rTowerR_CLOSED_LOOP_SLOT_UP);
        // turningConfig.closedLoop.maxMotion.maxVelocity(2000, rTowerR_CLOSED_LOOP_SLOT_UP);
        // turningConfig.closedLoop.maxMotion.allowedClosedLoopError(rTowerRPosTol, rTowerR_CLOSED_LOOP_SLOT_UP);
        // turningConfig.closedLoop.pidf(0.4, 0.0, 0.0, 0.0, rTowerR_CLOSED_LOOP_SLOT_UP);

        turningConfig.closedLoop.pid(0.0, 0.0, 0.0, ClosedLoopSlot.kSlot0);

        turningConfig.closedLoop.feedbackSensor(FeedbackSensor.kPrimaryEncoder);
        AbsoluteEncoderConfig absEncConfig = new AbsoluteEncoderConfig();
        absEncConfig.zeroOffset(0.0); // this needs to be set to the offset where the turret is "zeroed"
        absEncConfig.inverted(false);
        absEncConfig.positionConversionFactor(360);

        turningConfig.absoluteEncoder.apply(absEncConfig);
        turningConfig.closedLoop.feedbackSensor(FeedbackSensor.kPrimaryEncoder);
        turningConfig.smartCurrentLimit(25);
        //turningConfig.smartCurrentLimit(normalStallCurrentLimit, normalFreeCurrentLimit);

        turningMotor.configure(turningConfig, ResetMode.kResetSafeParameters, PersistMode.kPersistParameters);

    }
    //need to create enum for status of turret STOPPED, TARGETING, ON_TARGET
    public enum TurretStatus {
        STOPPED,
        TARGETING,
        ON_TARGET;
    }
}