// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import frc.robot.Constants;
import frc.robot.commands.*;

import com.revrobotics.spark.SparkMax;
import com.revrobotics.spark.config.SparkBaseConfig.IdleMode;
import com.thethriftybot.server.CAN;
import com.revrobotics.spark.config.SparkMaxConfig;

import java.io.ObjectInputFilter.Status;

import javax.lang.model.util.ElementScanner14;
import com.revrobotics.spark.ClosedLoopSlot;
import com.revrobotics.spark.FeedbackSensor;
import com.revrobotics.spark.SparkBase.ControlType;
import com.revrobotics.spark.SparkBase.PersistMode;
import com.revrobotics.spark.SparkLowLevel.MotorType;
import com.revrobotics.spark.SparkBase.ResetMode;

import edu.wpi.first.units.measure.Time;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import edu.wpi.first.wpilibj.DriverStation;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class PMGT extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    public static final double MaxRpm = 0;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // private final CANSparkMax armMotor = new CANSparkMax(5,
    // MotorType.kBrushless);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private Profiles currentProfile = Profiles.ALLDRIVE;
private SparkMax refMotor;
    /**
    *
    */
    public PMGT() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override

    public void periodic() {
        // This method will be called once per scheduler run
        // switch statement that changes the status based on the runtime match time        
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

public void setProfile(Profiles profile) {
        this.currentProfile = profile;
        updateActiveProfile();
    }

    public Profiles getCurrentProfile() {
        return this.currentProfile;
    }


private void updateActiveProfile(){

    SparkMaxConfig config = new SparkMaxConfig();
    for(int i = 0; i < 20; i++){
        // get the field with the name ID(i)S and set the spark max to that value
        try {
            java.lang.reflect.Field sl = currentProfile.getClass().getDeclaredField("ID" + (i+1) + "S");
            java.lang.reflect.Field fl = currentProfile.getClass().getDeclaredField("ID" + (i+1) + "F");
            refMotor = new SparkMax(i, MotorType.kBrushless);
            config.smartCurrentLimit(sl.getInt(currentProfile), fl.getInt(currentProfile));
            refMotor.configure(config, com.revrobotics.ResetMode.kNoResetSafeParameters,
             com.revrobotics.PersistMode.kNoPersistParameters);
        } catch (NoSuchFieldException | IllegalArgumentException | IllegalAccessException e) {
            e.printStackTrace();
        }
    }

    for(java.lang.reflect.Field f: currentProfile.getClass().getDeclaredFields()){

        if(f.getName().endsWith("S")){
            // set the spark max to the value of the field
            try {
                refMotor.set(f.getInt(currentProfile));
            } catch (IllegalArgumentException | IllegalAccessException e) {
                e.printStackTrace();
            }
        }
    }





}

    // We would like to make a Enum that contains 40 attributes that I labeled ID's
    // for S and for F.

    public enum Profiles {
        ALLDRIVE(60, 60, 20, 20, 60, 60, 20, 20,
                60, 60, 20, 20, 60, 60, 20, 20,
                10, 30, 10, 30, 10, 30, 10,
                30, 20, 20, 20, 20, 10, 10,
                20, 20, 10, 30, 10, 10,
                10, 10, 10, 30),
        ALLLAUNCH(30, 30, 20, 20, 30, 30, 20, 20,
                30, 30, 20, 20, 30, 30, 20, 20,
                40, 80, 40, 80, 40, 80, 40,
                80, 40, 60, 20, 40, 10, 10,
                20, 50, 20, 45, 10, 10,
                10, 10, 10, 40),
        DRIVE_WHILE_SHOOTING(30, 50, 20, 20, 30, 50, 20, 20,
                30, 50, 20, 20, 30, 50, 20, 20,
                40, 60, 40, 60, 40, 60, 40,
                60, 40, 50, 20, 40, 10, 10,
                20, 50, 20, 45, 10, 10,
                10, 10, 10, 40),
        DRIVE_WHILE_COLLECTING(30, 60, 20, 20, 30, 60, 20, 20,
                30, 60, 20, 20, 30, 60, 20, 20,
                40, 50, 40, 50, 40, 50, 40,
                50, 40, 50, 20, 40, 10, 10,
                20, 50, 20, 45, 10, 10,
                10, 10, 10, 40),
        CLIMB(60, 60, 20, 20, 60, 60, 20, 20,
                60, 60, 20, 20, 60, 60, 20, 20,
                10, 30, 10, 30, 10, 30, 10,
                30, 20, 20, 20, 20, 10, 10,
                20, 20, 10, 30, 40, 80,
                40, 80, 10, 30);

        int ID1S;
        int ID1F;
        int ID2S;
        int ID2F;
        int ID3S;
        int ID3F;
        int ID4S;
        int ID4F;
        int ID5S;
        int ID5F;
        int ID6S;
        int ID6F;
        int ID7S;
        int ID7F;
        int ID8S;
        int ID8F;
        int ID9S;
        int ID9F;
        int ID10S;
        int ID10F;
        int ID11S;
        int ID11F;
        int ID12S;
        int ID12F;
        int ID13S;
        int ID13F;
        int ID14S;
        int ID14F;
        int ID15S;
        int ID15F;
        int ID16S;
        int ID16F;
        int ID17S;
        int ID17F;
        int ID18S;
        int ID18F;
        int ID19S;
        int ID19F;
        int ID20S;
        int ID20F;

        Profiles(int ID1S, int ID1F, int ID2S, int ID2F, int ID3S, int ID3F, int ID4S, int ID4F, int ID5S, int ID5F,
                int ID6S, int ID6F, int ID7S, int ID7F, int ID8S, int ID8F, int ID9S, int ID9F, int ID10S,
                int ID10F, int ID11S, int ID11F, int ID12S, int ID12F, int ID13S, int ID13F, int ID14S,
                int ID14F, int ID15S, int ID15F, int ID16S, int ID16F, int ID17S, int ID17F, int ID18S,
                int ID18F, int ID19S, int ID19F, int ID20S, int ID20F) {
            this.ID1S = ID1S;
            this.ID1F = ID1F;
            this.ID2S = ID2S;
            this.ID2F = ID2F;
            this.ID3S = ID3S;
            this.ID3F = ID3F;
            this.ID4S = ID4S;
            this.ID4F = ID4F;
            this.ID5S = ID5S;
            this.ID5F = ID5F;
            this.ID6S = ID6S;
            this.ID6F = ID6F;
            this.ID7S = ID7S;
            this.ID7F = ID7F;
            this.ID8S = ID8S;
            this.ID8F = ID8F;
            this.ID9S = ID9S;
            this.ID9F = ID9F;
            this.ID10S = ID10S;
            this.ID10F = ID10F;
            this.ID11S = ID11S;
            this.ID11F = ID11F;
            this.ID12S = ID12S;
            this.ID12F = ID12F;
            this.ID13S = ID13S;
            this.ID13F = ID13F;
            this.ID14S = ID14S;
            this.ID14F = ID14F;
            this.ID15S = ID15S;
            this.ID15F = ID15F;
            this.ID16S = ID16S;
            this.ID16F = ID16F;
            this.ID17S = ID17S;
            this.ID17F = ID17F;
            this.ID18S = ID18S;
            this.ID18F = ID18F;
            this.ID19S = ID19S;
            this.ID19F = ID19F;
            this.ID20S = ID20S;
            this.ID20F = ID20F;
        }

    }
}
