// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands.FMS;

import edu.wpi.first.wpilibj2.command.Command;
import java.util.function.DoubleSupplier;

import frc.robot.RobotContainer;
import frc.robot.subsystems.FMSSystem;
import frc.robot.subsystems.FMSSystem.FMSStatus;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class CmdToggleOnShift extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private boolean onShift;
    private boolean is2_4;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    public CmdToggleOnShift() {

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // m_subsystem = subsystem;
        // addRequirements(m_subsystem);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        this.is2_4 = RobotContainer.getInstance().m_fmsSystem.getIs2_4();
        this.onShift = RobotContainer.getInstance().m_fmsSystem.getOnShift();
        switch (RobotContainer.getInstance().m_fmsSystem.getStatus()) {
            case TRANSITION:
                if (is2_4 = true) {
                    RobotContainer.getInstance().m_fmsSystem.setIs2_4(false);
                } else if (is2_4 = false) {
                    RobotContainer.getInstance().m_fmsSystem.setIs2_4(true);
                }
                break;

            case ALLIANCE_SHIFT_1:
                if (is2_4 = true) {
                    RobotContainer.getInstance().m_fmsSystem.setIs2_4(false);
                } else if (is2_4 = false) {
                    RobotContainer.getInstance().m_fmsSystem.setIs2_4(true);
                }

                if (onShift = true) {
                    RobotContainer.getInstance().m_fmsSystem.setOnShift(false);
                } else if (onShift = false) {
                    RobotContainer.getInstance().m_fmsSystem.setOnShift(true);
                }
                break;
            case ALLIANCE_SHIFT_2:
                 if (is2_4 = true) {
                    RobotContainer.getInstance().m_fmsSystem.setIs2_4(false);
                } else if (is2_4 = false) {
                    RobotContainer.getInstance().m_fmsSystem.setIs2_4(true);
                }

                if (onShift = true) {
                    RobotContainer.getInstance().m_fmsSystem.setOnShift(false);
                } else if (onShift = false) {
                    RobotContainer.getInstance().m_fmsSystem.setOnShift(true);
                }
                break;
            case ALLIANCE_SHIFT_3:
                 if (is2_4 = true) {
                    RobotContainer.getInstance().m_fmsSystem.setIs2_4(false);
                } else if (is2_4 = false) {
                    RobotContainer.getInstance().m_fmsSystem.setIs2_4(true);
                }

                if (onShift = true) {
                    RobotContainer.getInstance().m_fmsSystem.setOnShift(false);
                } else if (onShift = false) {
                    RobotContainer.getInstance().m_fmsSystem.setOnShift(true);
                }
                break;
            case ALLIANCE_SHIFT_4:
                 if (is2_4 = true) {
                    RobotContainer.getInstance().m_fmsSystem.setIs2_4(false);
                } else if (is2_4 = false) {
                    RobotContainer.getInstance().m_fmsSystem.setIs2_4(true);
                }

                if (onShift = true) {
                    RobotContainer.getInstance().m_fmsSystem.setOnShift(false);
                } else if (onShift = false) {
                    RobotContainer.getInstance().m_fmsSystem.setOnShift(true);
                }
                break;
            default:

                break;
        }

    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {

    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
