// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands.Intake;
import edu.wpi.first.wpilibj2.command.Command;
import java.util.function.DoubleSupplier;
import frc.robot.subsystems.Intake;
import frc.robot.RobotContainer;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class SetStatusIntake extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 private boolean bDone = false;
 private Intake.STATUS iStatus;
 private boolean bToggle = false;
 private Intake.STATUS currStatus;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    public SetStatusIntake(Intake.STATUS nStatus) {
        iStatus = nStatus;
        //addRequirements(RobotContainer.getInstance().m_intake);
        //this.bToggle = bToggle

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // m_subsystem = subsystem;
        // addRequirements(m_subsystem);    

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    public SetStatusIntake(Intake.STATUS nStatus, boolean bToggle) {
        iStatus = nStatus;
        this.bToggle = bToggle;
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        // Initialize the command with the target pose
        // m_subsystem.setNewTarget(targetPose);
        if (bToggle) {
            currStatus = RobotContainer.getInstance().m_intake.getStatus();
            if (currStatus == iStatus) {
            RobotContainer.getInstance().m_intake.setStatus(Intake.STATUS.HALF_EXTENDED);
            } else {
            RobotContainer.getInstance().m_intake.setStatus(iStatus);
            }
        } else {
        RobotContainer.getInstance().m_intake.setStatus(iStatus);
               }
               bDone = true; 
       
    }


    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return bDone;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
